### ISSUE TITLE
Internal link names not usable. Should be used user titles instead.

### ISSUE THREAD

**Issue by drfenixion** [galou/freecad.cross#31]
![freecad_cross_link_bad_name](https://github.com/galou/freecad.cross/assets/13005708/8c2194de-83ed-47f6-b085-2f46afbf54bc)
![freecad_cross_link_bad_name1](https://github.com/galou/freecad.cross/assets/13005708/4dea8416-5669-4ee0-ae4b-318139623e63)

it should be not "link004" but be "drone_frame_link" in image case.

**Comment by galou** [comment]
Again, a problem with missing documentation. CROSS uses the `Label2` property (called Description in the UI), if defined, then fallbacks to `Label`. The column `Description` is not visible by default anymore in v0.22. You need to right-click in the combo View and activate it.

The `Group` property is read-only for robots and should be considered as internal. I wonder why I didn't hide it.

Just to clarify things, FreeCAD objects have an immutable `Name` (also the Python variable for this object in `App.ActiveDocument`), a `Label`, which is unique in the document by default, and a `Label2`, which is completely constraint-free. CROSS uses `Label2` in priority in order to allow to have two robots with the same link and joint names (for example when importing twice the same URDF).
